version: "3.8"

services:
  # Prefect Server - Versão 1.4.1
  prefect-server:
    image: prefecthq/prefect:1.4.1-python3.8
    container_name: prefect-server
    ports:
      - "4200:4200"
      - "8080:8080"
    command: bash -c "prefect backend server && prefect server start"
    environment:
      - PREFECT__SERVER__HOST=0.0.0.0
      - PREFECT__SERVER__PORT=4200
      - PREFECT__SERVER__DATABASE__CONNECTION_URL=postgresql://prefect:prefect@postgres:5432/prefect_server
    depends_on:
      - postgres
    networks:
      - prefect-network
    volumes:
      - prefect-data:/root/.prefect
    restart: unless-stopped

  # Prefect Agent - Docker Agent
  prefect-agent:
    image: prefecthq/prefect:1.4.1-python3.8
    container_name: prefect-agent
    command: bash -c "prefect backend server && prefect agent local start --api http://prefect-server:4200"
    depends_on:
      - prefect-server
    environment:
      - PREFECT__CLOUD__API=http://prefect-server:4200
      - PREFECT__CLOUD__AGENT__LABELS=["local", "brt-pipeline"]
    networks:
      - prefect-network
    volumes:
      - prefect-data:/root/.prefect
      - ./:/app
    restart: unless-stopped

  # PostgreSQL - Banco de dados do Prefect Server
  postgres:
    image: postgres:13
    container_name: prefect-postgres
    environment:
      - POSTGRES_USER=prefect
      - POSTGRES_PASSWORD=prefect
      - POSTGRES_DB=prefect_server
    networks:
      - prefect-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  prefect-network:
    driver: bridge

volumes:
  prefect-data:
  postgres-data:
