# Configuração de perfil para DBT + BigQuery
# Copie este arquivo para ~/.dbt/profiles.yml

brt_pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: brt_dataset
      threads: 4
      timeout_seconds: 300
      location: southamerica-east1
      priority: interactive
      keyfile: "{{ env_var('GCP_CREDENTIALS_PATH') }}"
    
    prod:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: brt_dataset_prod
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: "{{ env_var('GCP_CREDENTIALS_PATH') }}"
