name: DBT Tests

on:
  push:
    branches: [ master, main ]
    paths:
      - 'dbt_brt/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'dbt_brt/**'

jobs:
  dbt-compile:
    name: DBT Compile & Test Syntax
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install DBT
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core==1.4.9 dbt-bigquery==1.4.3
        
    - name: List DBT models
      working-directory: ./dbt_brt
      run: |
        echo "DBT Project Structure:"
        find models -name "*.sql" -o -name "*.yml"
        
    - name: Validate DBT project structure
      working-directory: ./dbt_brt
      run: |
        echo "Validating DBT project..."
        test -f dbt_project.yml || (echo "dbt_project.yml missing" && exit 1)
        test -f profiles.yml || (echo "profiles.yml missing" && exit 1)
        test -d models/bronze || (echo "Bronze models missing" && exit 1)
        test -d models/silver || (echo "Silver models missing" && exit 1)
        test -d models/gold || (echo "Gold models missing" && exit 1)
        test -d tests || (echo "Tests missing" && exit 1)
        echo "DBT structure validated!"
        
    - name: Count DBT artifacts
      working-directory: ./dbt_brt
      run: |
        echo "=== DBT Artifacts Summary ==="
        echo "Models: $(find models -name '*.sql' | wc -l)"
        echo "Sources: $(find models -name 'sources.yml' -o -name '*sources.yml' | wc -l)"
        echo "Tests: $(find tests -name '*.sql' | wc -l)"
        echo "============================"
